### PR TITLE
knowledge graph embedding examples - Bin Shang

### PR DESCRIPTION
**Pull request by MiracleDesigner**
My name is Bin Shang. As requested by professor Yong You, I add three knowledge graph embedding examples DistMult, ComplEx and RotatE.  Please check the code and feel free to contact me if you have any questions.

### CODE REVIEW

**Review by FrankLeeeee — CHANGES_REQUESTED** [review]
Hi, please do not include data in the comit.

**Comment by MiracleDesigner** [comment]
您好，我已收到您的邮件。

**Comment by FrankLeeeee** [comment]
Hi, can you add a section `Prepare Dataset` in your `README.md` so that others know how handle the data processing. Meanwhile, have you verified the convergence of this model? If so, please attach the logs/plots here.

**Comment by MiracleDesigner** [comment]
> Hi, can you add a section `Prepare Dataset` in your `README.md` so that others know how handle the data processing. Meanwhile, have you verified the convergence of this model? If so, please attach the logs/plots here.

**Comment by MiracleDesigner** [comment]
> Hi, can you add a section `Prepare Dataset` in your `README.md` so that others know how handle the data processing. Meanwhile, have you verified the convergence of this model? If so, please attach the logs/plots here.

OK， I would remove the dataset and add `Prepare Dataset` in  `README.md`. The convergence of the model has been verified, and these three methods are the classic KGE algorithm.

**Pull request closed without merging**
